# Generated by Django 4.2.7 on 2025-08-14 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_hours', models.IntegerField(default=3)),
                ('semester', models.IntegerField(default=1)),
                ('year', models.IntegerField(null=True)),
                ('has_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_semester', models.IntegerField(default=1)),
                ('disable_evaluations', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50)),
                ('index_number', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('program', models.CharField(max_length=100)),
                ('campus', models.CharField(default='Sunyani', max_length=100)),
                ('status', models.CharField(default='Regular', max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_dept', to='selc_core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluated', models.BooleanField(default=False)),
                ('class_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_course', to='selc_core.classcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='selc_core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(default='')),
                ('answer_type', models.CharField(default='yes_no', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_category', to='selc_core.questioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='', max_length=300)),
                ('message', models.TextField(default='')),
                ('read', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LecturerRating',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('class_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lr_cc', to='selc_core.classcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lr_student', to='selc_core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='selc_core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationSuggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion', models.TextField(default='')),
                ('class_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_class_course', to='selc_core.classcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_student', to='selc_core.student')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('class_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_class_course', to='selc_core.classcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_student', to='selc_core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(default='')),
                ('class_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_class_course', to='selc_core.classcourse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_questionnaire', to='selc_core.questionnaire')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selc_core.student')),
            ],
        ),
        migrations.AddField(
            model_name='classcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_course', to='selc_core.course'),
        ),
        migrations.AddField(
            model_name='classcourse',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to='selc_core.lecturer'),
        ),
    ]
