# Generated by Django 4.2.7 on 2025-08-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selc_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsetting',
            name='disable_evaluations',
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='enable_evaluations',
            field=models.BooleanField(default=False),
        ),
    ]
