# Generated by Django 4.2.7 on 2025-09-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selc_core", "0002_remove_generalsetting_disable_evaluations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationsuggestion",
            name="sentiment",
            field=models.CharField(default="neutral", max_length=20),
        ),
    ]
