# Generated by Django 4.2.7 on 2025-09-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selc_core", "0003_evaluationsuggestion_sentiment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationsuggestion",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("POSITIVE", "positive"),
                    ("NEUTRAL", "netural"),
                    ("NEGATIVE", "negative"),
                ],
                default="neutral",
                max_length=20,
            ),
        ),
    ]
