# Generated by Django 4.2.7 on 2025-11-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selc_core", "0004_alter_evaluationsuggestion_sentiment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportFiles",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("file_name", models.TextField()),
                (
                    "report_file",
                    models.FileField(null=True, upload_to="evaluation-reports/"),
                ),
                ("file_type", models.CharField(default="", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="generalsetting",
            name="academic_year",
            field=models.IntegerField(default=2025),
        ),
    ]
