# Generated by Django 4.2.7 on 2025-11-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selc_core", "0005_reportfiles_generalsetting_academic_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportFile",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("file_name", models.TextField()),
                ("file", models.FileField(null=True, upload_to="evaluation-reports/")),
                ("file_type", models.CharField(default="", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ReportFiles",
        ),
    ]
