# Generated by Django 5.2.6 on 2025-12-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selc_core', '0006_reportfile_delete_reportfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
