# Generated by Django 5.2.6 on 2025-12-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selc_core', '0007_reportfile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcourse',
            name='is_accepting_response',
            field=models.BooleanField(default=False),
        ),
    ]
