# Generated by Django 5.2.6 on 2026-01-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selc_core', '0008_classcourse_is_accepting_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcourse',
            name='is_accepting_response',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='academic_year',
            field=models.IntegerField(default=2026),
        ),
    ]
