# Generated by Django 5.2.10 on 2026-01-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selc_core', '0009_alter_classcourse_is_accepting_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcourse',
            name='level',
            field=models.CharField(default='', max_length=4),
        ),
    ]
