# Generated by Django 5.2.10 on 2026-01-20 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selc_core', '0012_alter_evaluation_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='class_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='selc_core.classcourse'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='selc_core.student'),
        ),
    ]
