# Generated by Django 5.2.10 on 2026-01-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selc_core', '0013_alter_studentclass_class_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcourse',
            name='class_session',
            field=models.CharField(choices=[('MAINSTREAM', 'mainstream'), ('WEEKEND', 'weekend')], default='mainstream', max_length=20),
        ),
        migrations.AlterField(
            model_name='classcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_courses', to='selc_core.course'),
        ),
        migrations.AlterField(
            model_name='classcourse',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_courses', to='selc_core.lecturer'),
        ),
    ]
