# Generated by Django 5.2.10 on 2026-01-22 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selc_core', '0014_classcourse_class_session_alter_classcourse_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='semester_end_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 22, 15, 34, 47, 606433)),
        ),
    ]
