# Generated by Django 5.2.6 on 2026-02-09 06:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selc_core', '0015_generalsetting_semester_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='semester_end_date',
            field=models.DateField(default=datetime.date(2026, 2, 9)),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='selc_core.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='selc_core.department'),
        ),
    ]
