# Generated by Django 5.2.6 on 2026-02-12 00:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selc_core', '0016_student_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='semester_end_date',
            field=models.DateField(default=datetime.date(2026, 2, 12)),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires', to='selc_core.questioncategory'),
        ),
    ]
