# Generated by Django 5.2.6 on 2026-02-17 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selc_core', '0017_alter_generalsetting_semester_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='semester_end_date',
            field=models.DateField(default=datetime.date(2026, 2, 17)),
        ),
        migrations.AlterField(
            model_name='student',
            name='index_number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='reference_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
