# Generated by Django 5.2.6 on 2026-02-18 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selc_core', '0018_remove_student_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='semester_end_date',
            field=models.DateField(default=datetime.date(2026, 2, 18)),
        ),
    ]
