# Generated by Django 5.2.6 on 2026-02-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selc_core', '0019_alter_generalsetting_semester_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='index_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
